version: '3'
services:
  frontend:
    image: carmi321/wyf:frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
  
  backend:
    image: carmi321/wyf:backend
    ports:
      - "3000:3000"
